// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bookstore.proto

package bookstoreproto;

public final class Bookstore {
  private Bookstore() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bookstoreproto.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string find = 1;</code>
     */
    boolean hasFind();
    /**
     * <code>optional string find = 1;</code>
     */
    java.lang.String getFind();
    /**
     * <code>optional string find = 1;</code>
     */
    com.google.protobuf.ByteString
        getFindBytes();
  }
  /**
   * Protobuf type {@code bookstoreproto.Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:bookstoreproto.Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }

    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              find_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bookstoreproto.Bookstore.internal_static_bookstoreproto_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bookstoreproto.Bookstore.internal_static_bookstoreproto_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bookstoreproto.Bookstore.Request.class, bookstoreproto.Bookstore.Request.Builder.class);
    }

    public static com.google.protobuf.Parser<Request> PARSER =
        new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FIND_FIELD_NUMBER = 1;
    private java.lang.Object find_;
    /**
     * <code>optional string find = 1;</code>
     */
    public boolean hasFind() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string find = 1;</code>
     */
    public java.lang.String getFind() {
      java.lang.Object ref = find_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          find_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string find = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFindBytes() {
      java.lang.Object ref = find_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        find_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      find_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFindBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFindBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static bookstoreproto.Bookstore.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bookstoreproto.Bookstore.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bookstoreproto.Bookstore.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bookstoreproto.Bookstore.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bookstoreproto.Bookstore.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static bookstoreproto.Bookstore.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static bookstoreproto.Bookstore.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static bookstoreproto.Bookstore.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static bookstoreproto.Bookstore.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static bookstoreproto.Bookstore.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(bookstoreproto.Bookstore.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bookstoreproto.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bookstoreproto.Request)
        bookstoreproto.Bookstore.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bookstoreproto.Bookstore.internal_static_bookstoreproto_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bookstoreproto.Bookstore.internal_static_bookstoreproto_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                bookstoreproto.Bookstore.Request.class, bookstoreproto.Bookstore.Request.Builder.class);
      }

      // Construct using bookstoreproto.Bookstore.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        find_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bookstoreproto.Bookstore.internal_static_bookstoreproto_Request_descriptor;
      }

      public bookstoreproto.Bookstore.Request getDefaultInstanceForType() {
        return bookstoreproto.Bookstore.Request.getDefaultInstance();
      }

      public bookstoreproto.Bookstore.Request build() {
        bookstoreproto.Bookstore.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public bookstoreproto.Bookstore.Request buildPartial() {
        bookstoreproto.Bookstore.Request result = new bookstoreproto.Bookstore.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.find_ = find_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bookstoreproto.Bookstore.Request) {
          return mergeFrom((bookstoreproto.Bookstore.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(bookstoreproto.Bookstore.Request other) {
        if (other == bookstoreproto.Bookstore.Request.getDefaultInstance()) return this;
        if (other.hasFind()) {
          bitField0_ |= 0x00000001;
          find_ = other.find_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        bookstoreproto.Bookstore.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (bookstoreproto.Bookstore.Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object find_ = "";
      /**
       * <code>optional string find = 1;</code>
       */
      public boolean hasFind() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string find = 1;</code>
       */
      public java.lang.String getFind() {
        java.lang.Object ref = find_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            find_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string find = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFindBytes() {
        java.lang.Object ref = find_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          find_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string find = 1;</code>
       */
      public Builder setFind(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        find_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string find = 1;</code>
       */
      public Builder clearFind() {
        bitField0_ = (bitField0_ & ~0x00000001);
        find_ = getDefaultInstance().getFind();
        onChanged();
        return this;
      }
      /**
       * <code>optional string find = 1;</code>
       */
      public Builder setFindBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        find_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:bookstoreproto.Request)
    }

    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:bookstoreproto.Request)
  }

  public interface ReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bookstoreproto.Reply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .bookstoreproto.Reply.Book find = 1;</code>
     */
    boolean hasFind();
    /**
     * <code>optional .bookstoreproto.Reply.Book find = 1;</code>
     */
    bookstoreproto.Bookstore.Reply.Book getFind();
    /**
     * <code>optional .bookstoreproto.Reply.Book find = 1;</code>
     */
    bookstoreproto.Bookstore.Reply.BookOrBuilder getFindOrBuilder();

    /**
     * <code>optional string error = 100;</code>
     */
    boolean hasError();
    /**
     * <code>optional string error = 100;</code>
     */
    java.lang.String getError();
    /**
     * <code>optional string error = 100;</code>
     */
    com.google.protobuf.ByteString
        getErrorBytes();
  }
  /**
   * Protobuf type {@code bookstoreproto.Reply}
   */
  public static final class Reply extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:bookstoreproto.Reply)
      ReplyOrBuilder {
    // Use Reply.newBuilder() to construct.
    private Reply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Reply(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Reply defaultInstance;
    public static Reply getDefaultInstance() {
      return defaultInstance;
    }

    public Reply getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Reply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bookstoreproto.Bookstore.Reply.Book.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = find_.toBuilder();
              }
              find_ = input.readMessage(bookstoreproto.Bookstore.Reply.Book.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(find_);
                find_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 802: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              error_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return bookstoreproto.Bookstore.internal_static_bookstoreproto_Reply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return bookstoreproto.Bookstore.internal_static_bookstoreproto_Reply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              bookstoreproto.Bookstore.Reply.class, bookstoreproto.Bookstore.Reply.Builder.class);
    }

    public static com.google.protobuf.Parser<Reply> PARSER =
        new com.google.protobuf.AbstractParser<Reply>() {
      public Reply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Reply(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Reply> getParserForType() {
      return PARSER;
    }

    public interface BookOrBuilder extends
        // @@protoc_insertion_point(interface_extends:bookstoreproto.Reply.Book)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int32 isbn = 1;</code>
       */
      boolean hasIsbn();
      /**
       * <code>required int32 isbn = 1;</code>
       */
      int getIsbn();

      /**
       * <code>required string title = 2;</code>
       */
      boolean hasTitle();
      /**
       * <code>required string title = 2;</code>
       */
      java.lang.String getTitle();
      /**
       * <code>required string title = 2;</code>
       */
      com.google.protobuf.ByteString
          getTitleBytes();

      /**
       * <code>required string author = 3;</code>
       */
      boolean hasAuthor();
      /**
       * <code>required string author = 3;</code>
       */
      java.lang.String getAuthor();
      /**
       * <code>required string author = 3;</code>
       */
      com.google.protobuf.ByteString
          getAuthorBytes();
    }
    /**
     * Protobuf type {@code bookstoreproto.Reply.Book}
     */
    public static final class Book extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:bookstoreproto.Reply.Book)
        BookOrBuilder {
      // Use Book.newBuilder() to construct.
      private Book(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Book(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Book defaultInstance;
      public static Book getDefaultInstance() {
        return defaultInstance;
      }

      public Book getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Book(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                isbn_ = input.readInt32();
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                title_ = bs;
                break;
              }
              case 26: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000004;
                author_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bookstoreproto.Bookstore.internal_static_bookstoreproto_Reply_Book_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bookstoreproto.Bookstore.internal_static_bookstoreproto_Reply_Book_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                bookstoreproto.Bookstore.Reply.Book.class, bookstoreproto.Bookstore.Reply.Book.Builder.class);
      }

      public static com.google.protobuf.Parser<Book> PARSER =
          new com.google.protobuf.AbstractParser<Book>() {
        public Book parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Book(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Book> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int ISBN_FIELD_NUMBER = 1;
      private int isbn_;
      /**
       * <code>required int32 isbn = 1;</code>
       */
      public boolean hasIsbn() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 isbn = 1;</code>
       */
      public int getIsbn() {
        return isbn_;
      }

      public static final int TITLE_FIELD_NUMBER = 2;
      private java.lang.Object title_;
      /**
       * <code>required string title = 2;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string title = 2;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string title = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int AUTHOR_FIELD_NUMBER = 3;
      private java.lang.Object author_;
      /**
       * <code>required string author = 3;</code>
       */
      public boolean hasAuthor() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string author = 3;</code>
       */
      public java.lang.String getAuthor() {
        java.lang.Object ref = author_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            author_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string author = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAuthorBytes() {
        java.lang.Object ref = author_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          author_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        isbn_ = 0;
        title_ = "";
        author_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasIsbn()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasTitle()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasAuthor()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, isbn_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getTitleBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getAuthorBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, isbn_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getTitleBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getAuthorBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static bookstoreproto.Bookstore.Reply.Book parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static bookstoreproto.Bookstore.Reply.Book parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static bookstoreproto.Bookstore.Reply.Book parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static bookstoreproto.Bookstore.Reply.Book parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static bookstoreproto.Bookstore.Reply.Book parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static bookstoreproto.Bookstore.Reply.Book parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static bookstoreproto.Bookstore.Reply.Book parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static bookstoreproto.Bookstore.Reply.Book parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static bookstoreproto.Bookstore.Reply.Book parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static bookstoreproto.Bookstore.Reply.Book parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(bookstoreproto.Bookstore.Reply.Book prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code bookstoreproto.Reply.Book}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:bookstoreproto.Reply.Book)
          bookstoreproto.Bookstore.Reply.BookOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return bookstoreproto.Bookstore.internal_static_bookstoreproto_Reply_Book_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return bookstoreproto.Bookstore.internal_static_bookstoreproto_Reply_Book_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  bookstoreproto.Bookstore.Reply.Book.class, bookstoreproto.Bookstore.Reply.Book.Builder.class);
        }

        // Construct using bookstoreproto.Bookstore.Reply.Book.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          isbn_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          title_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          author_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return bookstoreproto.Bookstore.internal_static_bookstoreproto_Reply_Book_descriptor;
        }

        public bookstoreproto.Bookstore.Reply.Book getDefaultInstanceForType() {
          return bookstoreproto.Bookstore.Reply.Book.getDefaultInstance();
        }

        public bookstoreproto.Bookstore.Reply.Book build() {
          bookstoreproto.Bookstore.Reply.Book result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public bookstoreproto.Bookstore.Reply.Book buildPartial() {
          bookstoreproto.Bookstore.Reply.Book result = new bookstoreproto.Bookstore.Reply.Book(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.isbn_ = isbn_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.title_ = title_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.author_ = author_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof bookstoreproto.Bookstore.Reply.Book) {
            return mergeFrom((bookstoreproto.Bookstore.Reply.Book)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(bookstoreproto.Bookstore.Reply.Book other) {
          if (other == bookstoreproto.Bookstore.Reply.Book.getDefaultInstance()) return this;
          if (other.hasIsbn()) {
            setIsbn(other.getIsbn());
          }
          if (other.hasTitle()) {
            bitField0_ |= 0x00000002;
            title_ = other.title_;
            onChanged();
          }
          if (other.hasAuthor()) {
            bitField0_ |= 0x00000004;
            author_ = other.author_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasIsbn()) {
            
            return false;
          }
          if (!hasTitle()) {
            
            return false;
          }
          if (!hasAuthor()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          bookstoreproto.Bookstore.Reply.Book parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (bookstoreproto.Bookstore.Reply.Book) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int isbn_ ;
        /**
         * <code>required int32 isbn = 1;</code>
         */
        public boolean hasIsbn() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 isbn = 1;</code>
         */
        public int getIsbn() {
          return isbn_;
        }
        /**
         * <code>required int32 isbn = 1;</code>
         */
        public Builder setIsbn(int value) {
          bitField0_ |= 0x00000001;
          isbn_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 isbn = 1;</code>
         */
        public Builder clearIsbn() {
          bitField0_ = (bitField0_ & ~0x00000001);
          isbn_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object title_ = "";
        /**
         * <code>required string title = 2;</code>
         */
        public boolean hasTitle() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string title = 2;</code>
         */
        public java.lang.String getTitle() {
          java.lang.Object ref = title_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              title_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string title = 2;</code>
         */
        public com.google.protobuf.ByteString
            getTitleBytes() {
          java.lang.Object ref = title_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            title_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string title = 2;</code>
         */
        public Builder setTitle(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          title_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string title = 2;</code>
         */
        public Builder clearTitle() {
          bitField0_ = (bitField0_ & ~0x00000002);
          title_ = getDefaultInstance().getTitle();
          onChanged();
          return this;
        }
        /**
         * <code>required string title = 2;</code>
         */
        public Builder setTitleBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          title_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object author_ = "";
        /**
         * <code>required string author = 3;</code>
         */
        public boolean hasAuthor() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required string author = 3;</code>
         */
        public java.lang.String getAuthor() {
          java.lang.Object ref = author_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              author_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string author = 3;</code>
         */
        public com.google.protobuf.ByteString
            getAuthorBytes() {
          java.lang.Object ref = author_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            author_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string author = 3;</code>
         */
        public Builder setAuthor(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          author_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string author = 3;</code>
         */
        public Builder clearAuthor() {
          bitField0_ = (bitField0_ & ~0x00000004);
          author_ = getDefaultInstance().getAuthor();
          onChanged();
          return this;
        }
        /**
         * <code>required string author = 3;</code>
         */
        public Builder setAuthorBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          author_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:bookstoreproto.Reply.Book)
      }

      static {
        defaultInstance = new Book(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:bookstoreproto.Reply.Book)
    }

    private int bitField0_;
    public static final int FIND_FIELD_NUMBER = 1;
    private bookstoreproto.Bookstore.Reply.Book find_;
    /**
     * <code>optional .bookstoreproto.Reply.Book find = 1;</code>
     */
    public boolean hasFind() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .bookstoreproto.Reply.Book find = 1;</code>
     */
    public bookstoreproto.Bookstore.Reply.Book getFind() {
      return find_;
    }
    /**
     * <code>optional .bookstoreproto.Reply.Book find = 1;</code>
     */
    public bookstoreproto.Bookstore.Reply.BookOrBuilder getFindOrBuilder() {
      return find_;
    }

    public static final int ERROR_FIELD_NUMBER = 100;
    private java.lang.Object error_;
    /**
     * <code>optional string error = 100;</code>
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string error = 100;</code>
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          error_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string error = 100;</code>
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      find_ = bookstoreproto.Bookstore.Reply.Book.getDefaultInstance();
      error_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasFind()) {
        if (!getFind().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, find_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(100, getErrorBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, find_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(100, getErrorBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static bookstoreproto.Bookstore.Reply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bookstoreproto.Bookstore.Reply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bookstoreproto.Bookstore.Reply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static bookstoreproto.Bookstore.Reply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static bookstoreproto.Bookstore.Reply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static bookstoreproto.Bookstore.Reply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static bookstoreproto.Bookstore.Reply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static bookstoreproto.Bookstore.Reply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static bookstoreproto.Bookstore.Reply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static bookstoreproto.Bookstore.Reply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(bookstoreproto.Bookstore.Reply prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bookstoreproto.Reply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bookstoreproto.Reply)
        bookstoreproto.Bookstore.ReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return bookstoreproto.Bookstore.internal_static_bookstoreproto_Reply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return bookstoreproto.Bookstore.internal_static_bookstoreproto_Reply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                bookstoreproto.Bookstore.Reply.class, bookstoreproto.Bookstore.Reply.Builder.class);
      }

      // Construct using bookstoreproto.Bookstore.Reply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFindFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (findBuilder_ == null) {
          find_ = bookstoreproto.Bookstore.Reply.Book.getDefaultInstance();
        } else {
          findBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        error_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return bookstoreproto.Bookstore.internal_static_bookstoreproto_Reply_descriptor;
      }

      public bookstoreproto.Bookstore.Reply getDefaultInstanceForType() {
        return bookstoreproto.Bookstore.Reply.getDefaultInstance();
      }

      public bookstoreproto.Bookstore.Reply build() {
        bookstoreproto.Bookstore.Reply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public bookstoreproto.Bookstore.Reply buildPartial() {
        bookstoreproto.Bookstore.Reply result = new bookstoreproto.Bookstore.Reply(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (findBuilder_ == null) {
          result.find_ = find_;
        } else {
          result.find_ = findBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.error_ = error_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof bookstoreproto.Bookstore.Reply) {
          return mergeFrom((bookstoreproto.Bookstore.Reply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(bookstoreproto.Bookstore.Reply other) {
        if (other == bookstoreproto.Bookstore.Reply.getDefaultInstance()) return this;
        if (other.hasFind()) {
          mergeFind(other.getFind());
        }
        if (other.hasError()) {
          bitField0_ |= 0x00000002;
          error_ = other.error_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasFind()) {
          if (!getFind().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        bookstoreproto.Bookstore.Reply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (bookstoreproto.Bookstore.Reply) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private bookstoreproto.Bookstore.Reply.Book find_ = bookstoreproto.Bookstore.Reply.Book.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          bookstoreproto.Bookstore.Reply.Book, bookstoreproto.Bookstore.Reply.Book.Builder, bookstoreproto.Bookstore.Reply.BookOrBuilder> findBuilder_;
      /**
       * <code>optional .bookstoreproto.Reply.Book find = 1;</code>
       */
      public boolean hasFind() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .bookstoreproto.Reply.Book find = 1;</code>
       */
      public bookstoreproto.Bookstore.Reply.Book getFind() {
        if (findBuilder_ == null) {
          return find_;
        } else {
          return findBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .bookstoreproto.Reply.Book find = 1;</code>
       */
      public Builder setFind(bookstoreproto.Bookstore.Reply.Book value) {
        if (findBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          find_ = value;
          onChanged();
        } else {
          findBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .bookstoreproto.Reply.Book find = 1;</code>
       */
      public Builder setFind(
          bookstoreproto.Bookstore.Reply.Book.Builder builderForValue) {
        if (findBuilder_ == null) {
          find_ = builderForValue.build();
          onChanged();
        } else {
          findBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .bookstoreproto.Reply.Book find = 1;</code>
       */
      public Builder mergeFind(bookstoreproto.Bookstore.Reply.Book value) {
        if (findBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              find_ != bookstoreproto.Bookstore.Reply.Book.getDefaultInstance()) {
            find_ =
              bookstoreproto.Bookstore.Reply.Book.newBuilder(find_).mergeFrom(value).buildPartial();
          } else {
            find_ = value;
          }
          onChanged();
        } else {
          findBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .bookstoreproto.Reply.Book find = 1;</code>
       */
      public Builder clearFind() {
        if (findBuilder_ == null) {
          find_ = bookstoreproto.Bookstore.Reply.Book.getDefaultInstance();
          onChanged();
        } else {
          findBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .bookstoreproto.Reply.Book find = 1;</code>
       */
      public bookstoreproto.Bookstore.Reply.Book.Builder getFindBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getFindFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .bookstoreproto.Reply.Book find = 1;</code>
       */
      public bookstoreproto.Bookstore.Reply.BookOrBuilder getFindOrBuilder() {
        if (findBuilder_ != null) {
          return findBuilder_.getMessageOrBuilder();
        } else {
          return find_;
        }
      }
      /**
       * <code>optional .bookstoreproto.Reply.Book find = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          bookstoreproto.Bookstore.Reply.Book, bookstoreproto.Bookstore.Reply.Book.Builder, bookstoreproto.Bookstore.Reply.BookOrBuilder> 
          getFindFieldBuilder() {
        if (findBuilder_ == null) {
          findBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              bookstoreproto.Bookstore.Reply.Book, bookstoreproto.Bookstore.Reply.Book.Builder, bookstoreproto.Bookstore.Reply.BookOrBuilder>(
                  getFind(),
                  getParentForChildren(),
                  isClean());
          find_ = null;
        }
        return findBuilder_;
      }

      private java.lang.Object error_ = "";
      /**
       * <code>optional string error = 100;</code>
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string error = 100;</code>
       */
      public java.lang.String getError() {
        java.lang.Object ref = error_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            error_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string error = 100;</code>
       */
      public com.google.protobuf.ByteString
          getErrorBytes() {
        java.lang.Object ref = error_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          error_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string error = 100;</code>
       */
      public Builder setError(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string error = 100;</code>
       */
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000002);
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      /**
       * <code>optional string error = 100;</code>
       */
      public Builder setErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        error_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:bookstoreproto.Reply)
    }

    static {
      defaultInstance = new Reply(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:bookstoreproto.Reply)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bookstoreproto_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bookstoreproto_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bookstoreproto_Reply_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bookstoreproto_Reply_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bookstoreproto_Reply_Book_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bookstoreproto_Reply_Book_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017bookstore.proto\022\016bookstoreproto\"\027\n\007Req" +
      "uest\022\014\n\004find\030\001 \001(\t\"u\n\005Reply\022(\n\004find\030\001 \001(" +
      "\0132\032.bookstoreproto.Reply.Book\022\r\n\005error\030d" +
      " \001(\t\0323\n\004Book\022\014\n\004isbn\030\001 \002(\005\022\r\n\005title\030\002 \002(" +
      "\t\022\016\n\006author\030\003 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_bookstoreproto_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bookstoreproto_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bookstoreproto_Request_descriptor,
        new java.lang.String[] { "Find", });
    internal_static_bookstoreproto_Reply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bookstoreproto_Reply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bookstoreproto_Reply_descriptor,
        new java.lang.String[] { "Find", "Error", });
    internal_static_bookstoreproto_Reply_Book_descriptor =
      internal_static_bookstoreproto_Reply_descriptor.getNestedTypes().get(0);
    internal_static_bookstoreproto_Reply_Book_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bookstoreproto_Reply_Book_descriptor,
        new java.lang.String[] { "Isbn", "Title", "Author", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
